"""empty message

Revision ID: b80502913703
Revises: 23fcf1798c2b
Create Date: 2020-01-14 11:29:34.079205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80502913703'
down_revision = '23fcf1798c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('img_file', sa.String(), nullable=False),
    sa.Column('index_case', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    # ### end Alembic commands ###
